name: CI/CD Breast Cancer API

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t breast_api .

    - name: Run Docker container
      run: |
        docker run -d --name breast_api_test -p 5000:5000 breast_api
        sleep 10  # espera que la API arranque

    - name: Test API endpoint
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"features": [17.99,10.38,122.8,1001.0,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.905,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189]}' \
        http://localhost:5000/predict

    - name: Stop Docker container
      run: docker stop breast_api_test

    # --- NUEVO BLOQUE: login y push a Docker Hub ---
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/breast_api:latest
        docker tag breast_api $IMAGE_NAME
        docker push $IMAGE_NAME
